### ISSUE TITLE
VS2022 warning treated as error 

### ISSUE THREAD

**Issue by nil-ref** [ntoskrnl7/ldk#11]
`\crtsys\build_2022_x64\_deps\ldk-src\src\kernel32\synchapi.c(731,19): error C2220: warning treated as error [\crtsys\build_2022_x64\_deps\ldk-build\Ldk.vcxproj]

\crtsys\build_2022_x64\_deps\ldk-src\src\kernel32\synchapi.c(731,19): warning C4996: 'ExAllocatePoolWithTag': ExAllocatePoolWithTag is deprecated, use ExAllocatePool2. [\crtsys\build_2022_x64\_deps\ldk-build\Ldk.vcxproj]
`

**Comment by ntoskrnl7** [comment]
0.75.0
fix: WDK 10.0.22621.0 warning treated as error

> `\crtsys\build_2022_x64_deps\ldk-src\src\kernel32\synchapi.c(731,19): error C2220: warning treated as error [\crtsys\build_2022_x64_deps\ldk-build\Ldk.vcxproj]
> 
> \crtsys\build_2022_x64_deps\ldk-src\src\kernel32\synchapi.c(731,19): warning C4996: 'ExAllocatePoolWithTag': ExAllocatePoolWithTag is deprecated, use ExAllocatePool2. [\crtsys\build_2022_x64_deps\ldk-build\Ldk.vcxproj] `
